#server:
#  port: 8080
#
#spring:
#  profiles:
#    active: dev
#  application:
#    name: catatan-keuangan
#  datasource:
##    url: jdbc:postgresql://localhost:5432/postgres
#    url: jdbc:postgresql://172.17.0.2:5432/postgres
#    username: postgres
#    password: jancok123
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop