name: CI/CD Pipeline

# Event yang memicu workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job pertama: Build dan Test
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup JDK 8 menggunakan Temurin
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin

      # 3. Build Maven Project
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Debug: List files in the target directory
      - name: List files in target directory
        run: ls -l target/

      # 5. Run Unit Tests
  #      - name: Run Unit Tests
  #        run: mvn test

  # Job kedua: Build dan Push Docker Image
  docker_build_and_push:
    needs: build_and_test  # Job ini hanya berjalan jika build_and_test sukses
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Pastikan file .jar ada
      - name: Verify JAR File Exists
        run: |
          # Pastikan file .jar ada di direktori target atau build/libs
          if [ ! -f target/catatan-keuangan-0.0.1-SNAPSHOT.jar ]; then
          if [ ! -f build/libs/catatan-keuangan-0.0.1-SNAPSHOT.jar ]; then
           echo "Error: catatan-keuangan-0.0.1-SNAPSHOT.jar not found in target/ or build/libs/ directory!"
           exit 1
          fi
          fi
          
      # 4. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t catatan-keuangan:${{ github.sha }} .
          docker tag catatan-keuangan:${{ github.sha }} my-dockerhub-user/catatan-keuangan:latest

      # 5. Push Docker image
      - name: Push Docker Image
        run: |
          docker push my-dockerhub-user/catatan-keuangan:latest