name: CI/CD Pipeline

# Event yang memicu workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job pertama: Build dan Test
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup JDK 8 menggunakan Temurin
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build Maven Project
      - name: Build with Maven
        run: mvn clean package -DskipTests=True

      # Debug: List files in the target directory
      - name: List files in target directory
        run: ls -l target/

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
            name: build-jar
            path: target/catatan-keuangan*.jar

      # 6. Run Unit Tests
  #      - name: Run Unit Tests
  #        run: mvn test

  # Job kedua: Build dan Push Docker Image
  docker_build_and_push:
    needs: build_and_test  # Job ini hanya berjalan jika build_and_test sukses
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Checkout kode dari repository
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
            name: build-jar

      # Debug: List files in the target directory
      - name: List files in target directory
        run: |
          echo "Checking target directory:"
          pwd
          ls -l 

      # Pastikan direktori target ada
      - name: Create target directory if it doesn't exist
        run: |
          mkdir -p target
          pwd

      # Pindahkan file JAR ke target directory (atau lokasi lain yang diinginkan)
      - name: Move JAR file to target directory
        run: |
          mv /home/runner/work/catatan-keuangan/catatan-keuangan/catatan-keuangan*.jar target/

      # Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t catatan-keuangan:${{ github.sha }} .
          docker tag catatan-keuangan:${{ github.sha }} my-dockerhub-user/catatan-keuangan:latest

      # Push Docker image
      - name: Push Docker Image
        run: |
          docker push my-dockerhub-user/catatan-keuangan:latest