name: CI/CD Pipeline

# Event yang memicu workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job pertama: Build dan Test
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup JDK 8 menggunakan Temurin
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin

      # 3. Build Maven Project
      - name: Build with Maven
        run: mvn clean package -DskipTests=True

      # 4. Debug: List files in the target directory
      - name: List files in target directory
        run: ls -l target/

      # 5. Run Unit Tests
  #      - name: Run Unit Tests
  #        run: mvn test

  # Job kedua: Build dan Push Docker Image
  docker_build_and_push:
    needs: build_and_test  # Job ini hanya berjalan jika build_and_test sukses
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Debug: List files in the target directory
      - name: List files in target directory
        run: |
          echo "Checking target directory:"
          ls -l target/
          ls -l app/

      # Verify single JAR file exists
      - name: Verify single JAR file exists
        run: |
          JAR_COUNT=$(ls -1 target/catatan-keuangan*.jar | wc -l)
          if [ "$JAR_COUNT" -ne 1 ]; then
            echo "Error: Found $JAR_COUNT JAR files in target/ but expected exactly 1!"
            exit 1
          fi

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t catatan-keuangan:${{ github.sha }} .
          docker tag catatan-keuangan:${{ github.sha }} my-dockerhub-user/catatan-keuangan:latest

      # Push Docker image
      - name: Push Docker Image
        run: |
          docker push my-dockerhub-user/catatan-keuangan:latest